server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false

  redis:
    host: localhost
    port: 6379

app:
  jwt:
    secret: mySuperSecretKeyForJWTThatIsAtLeast32CharactersLong
    refreshSecret: mySuperSecretRefreshKeyForJWTThatIsAtLeast32CharactersLong
    expirationMs: 900000
    refreshExpirationMs: 604800000
  otp:
    provider: mock
    length: 6
    expiration-minutes: 5
  auth:
    admin-email: admin@puntog.com
    admin-password: admin123
    advertiser-email: anunciante@tosty.com
    advertiser-password: tosty123

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
