server:
  port: 8093

spring:
  application:
    name: coupon-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:coupon_db}
    username: ${POSTGRES_USER:gasolinera_user}
    password: ${POSTGRES_PASSWORD:gasolinera_pass}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:gasolinera_user}
    password: ${RABBITMQ_PASS:gasolinera_pass}
    virtual-host: ${RABBITMQ_VHOST:gasolinera_vhost}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:coupondb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: gasolinera_user
    password: gasolinera_pass
    virtual-host: gasolinera_vhost

  cloud:
    vault:
      enabled: false  # Disabled for local development
      scheme: http
      host: localhost
      port: 8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:myroottoken}
      kv:
        enabled: false
        backend: secret
        profile-separator: /
        default-context: application
        application-name: ${spring.application.name}
