# Configuración de Prometheus para Gasolinera JSM
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "gasolinera-jsm"
    environment: "${ENVIRONMENT:-development}"

# Configuración de reglas de alertas
rule_files:
  - "alert_rules.yml"
  - "business_rules.yml"

# Configuración de Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Configuración de scraping
scrape_configs:
  # API Gateway
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ["prometheus"]

  # Auth Service
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8081"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scrape_timeout: 5s

  # Station Service
  - job_name: "station-service"
    static_configs:
      - targets: ["station-service:8082"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scrape_timeout: 5s

  # Coupon Service
  - job_name: "coupon-service"
    static_configs:
      - targets: ["coupon-service:8083"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scrape_timeout: 5s

  # Raffle Service
  - job_name: "raffle-service"
    static_configs:
      - targets: ["raffle-service:8084"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scrape_timeout: 5s

  # Redemption Service
  - job_name: "redemption-service"
    static_configs:
      - targets: ["redemption-service:8085"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scrape_timeout: 5s

  # Ad Engine Service
  - job_name: "ad-engine-service"
    static_configs:
      - targets: ["ad-engine-service:8086"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s
    scrape_timeout: 5s

  # Message Improver Service
  - job_name: "message-improver-service"
    static_configs:
      - targets: ["message-improver-service:8087"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s
    scrape_timeout: 5s

  # PostgreSQL Exporter
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
    scrape_timeout: 5s

  # Redis Exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    scrape_timeout: 5s

  # RabbitMQ Exporter
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]
    scrape_interval: 30s
    scrape_timeout: 5s

  # Node Exporter (métricas del sistema)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    scrape_timeout: 5s

  # Health checks endpoints
  - job_name: "health-checks"
    static_configs:
      - targets:
          - "api-gateway:8080"
          - "auth-service:8081"
          - "station-service:8082"
          - "coupon-service:8083"
          - "raffle-service:8084"
          - "redemption-service:8085"
    metrics_path: "/health"
    scrape_interval: 10s
    scrape_timeout: 3s
    params:
      format: ["prometheus"]

# Configuración de service discovery (para Kubernetes)
# - job_name: 'kubernetes-pods'
#   kubernetes_sd_configs:
#     - role: pod
#   relabel_configs:
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#       action: keep
#       regex: true
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#       action: replace
#       target_label: __metrics_path__
#       regex: (.+)
#     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
#       action: replace
#       regex: ([^:]+)(?::\d+)?;(\d+)
#       replacement: $1:$2
#       target_label: __address__
#     - action: labelmap
#       regex: __meta_kubernetes_pod_label_(.+)
#     - source_labels: [__meta_kubernetes_namespace]
#       action: replace
#       target_label: kubernetes_namespace
#     - source_labels: [__meta_kubernetes_pod_name]
#       action: replace
#       target_label: kubernetes_pod_name

# Configuración de almacenamiento
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Configuración de servidor web
web:
  console.templates: /etc/prometheus/consoles
  console.libraries: /etc/prometheus/console_libraries
  enable-lifecycle: true
  enable-admin-api: true
