package com.gasolinerajsm.messaging.events

enum class AuditType {
    USER_REGISTRATION,
    USER_LOGIN,
    USER_LOGOUT,
    COUPON_CREATED,
    COUPON_REDEEMED,
    COUPON_VALIDATED,
    RAFFLE_CREATED,
    RAFFLE_ENTRY,
    RAFFLE_DRAW,
    AD_VIEWED,
    AD_CLICKED,
    TICKET_GENERATED,
    TICKET_MULTIPLIED,
    PRIZE_AWARDED,
    SYSTEM_ERROR,
    SECURITY_VIOLATION,
    DATA_EXPORT,
    DATA_IMPORT,
    CONFIGURATION_CHANGE,
    PAYMENT_PROCESSED
}